name: Lint and Test Charts

on:
  push:
    paths:
      - '.helm/**'
  pull_request:
    paths:
      - '.helm/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.2.1
      - run: ct lint --config ${{ github.workspace }}/.github/chart-testing.yml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.21.12
          - v1.22.9
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.21.12
          - v1.22.9
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.2.1
      - run: ct install --config ${{ github.workspace }}/.github/chart-testing.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
      - install-chart
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Set up google credentials
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Package Charts
        run: helm package .helm/linxoconnectconnector
      - name: Get Chart version
        id: get-chart-version
        uses:  KJ002/read-yaml@1.6
        with: 
          file: ${{ github.workspace }}/.helm/linxoconnectconnector/Chart.yaml
          key-path: '["version"]'
      - name: Push Charts to Artifact Registry
        run: helm push charts-${{ steps.get-chart-version.outputs.data }}.tgz oci://europe-docker.pkg.dev/algoan-prod/linxo-connect-connector
