
name: Run Build, tests and Publish (workflow_dispatch)
on:
  workflow_dispatch:
    inputs:
      ref:
        description: |
          The branch, tag or SHA to checkout. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that event.
          Otherwise, uses the default branch.
        required: false
        default: master
  pull_request:
    paths-ignore:
      - .helm/**
  push:
    paths-ignore:
      - .helm/**
    branches-ignore:
      - gh-pages

env:
  NODE_ENV: test
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Run Build, Lint and Tests
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Setup the node environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Cache dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # Install dependencies
      - run: npm ci --prefer-offline
      # Build application
      - run: npm run build
      # Run lint
      - run: npm run lint
      # Run unit tests
      - run: npm run test
      # Run functional tests with coverage
      - run: npm run test:e2e:cov

  publish:
    runs-on: ubuntu-latest
    name: Push the docker image to dockerhub
    needs: test_workflow
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch' }}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Setup the node environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Install dependencies
      - run: npm ci --prefer-offline
      - run: npx semantic-release
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_GHA_PAT }}
